TMAN.LABOPS.FRONT.WEBUI/Tman.LabOps.WebUI.MVC/Controllers/EquipmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Tman.LabOps.Infrastructure.CrossCutting.DTOs.Equipamento;
using Tman.LabOps.Infrastructure.CrossCutting.DTOs.Fabricante;
using Tman.LabOps.Infrastructure.CrossCutting.DTOs.Situacao;
using Tman.LabOps.Infrastructure.CrossCutting.DTOs.TiposEquipamentos;
using Tman.LabOps.WebUI.Application.Interfaces;

#pragma warning disable IDE0290

namespace Tman.LabOps.WebUI.MVC.Controllers
{
    [Route("Equipamentos")]
    public class EquipmentController : Controller
    {
        private readonly IHandlersEquipment _handlerEquipment;
        private readonly IHandlerManufacturer _handlerManufacturer;
        private readonly IHandlerEquipmentType _handlerEquipmentType;
        private readonly IHandlerSituation _handlerSituation;

        public EquipmentController(IHandlersEquipment handlerEquipment, IHandlerManufacturer handlerManufacturer,
            IHandlerEquipmentType handlerEquipmentType, IHandlerSituation handlerSituation)
        {
            _handlerEquipment = handlerEquipment;
            _handlerManufacturer = handlerManufacturer;
            _handlerEquipmentType = handlerEquipmentType;
            _handlerSituation = handlerSituation;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var dados = await _handlerEquipment.GetAllEquipment();
            return View(dados);
        }

        [HttpGet("Detalhes")]
        public async Task<IActionResult> Details(int id)
        {
            var dados = await _handlerEquipment.GetEquipmentById(id);
            return PartialView("_Details", dados);
        }

        [HttpGet("Cadastro")]
        public async Task<IActionResult> Register()
        {
            var vManufacturers = await _handlerManufacturer.GetAllManufacturers();
            ViewBag.ValuesEquipment = new SelectList(vManufacturers, nameof(FabricanteDTO.Id), nameof(FabricanteDTO.Nome));

            var vEquipmentType = await _handlerEquipmentType.GetAllEquipmentType();
            ViewBag.ValuesEquipmentType = new SelectList(vEquipmentType, nameof(TipoEquipamentoDTO.Id), nameof(TipoEquipamentoDTO.Descricao));

            var vSituation = await _handlerSituation.GetAllSituation();
            ViewBag.ValuesSituation = new SelectList(vSituation, nameof(SituacaoDTO.Id), nameof(SituacaoDTO.Descricao));

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(NewEquipamentoDTO criarNovoE)
        {
            await _handlerEquipment.RegisterEquipment(criarNovoE);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet("Editar")]
        public async Task<IActionResult> Edit(int id)
        {
            var equipEdit = await _handlerEquipment.GetEquipmentById(id);

            var vManufacturers = await _handlerManufacturer.GetAllManufacturers();
            ViewBag.ValuesEquipment = new SelectList(vManufacturers, nameof(FabricanteDTO.Id), nameof(FabricanteDTO.Nome), equipEdit.FabricanteDto.Id);

            var vEquipmentType = await _handlerEquipmentType.GetAllEquipmentType();
            ViewBag.ValuesEquipmentType = new SelectList(vEquipmentType, nameof(TipoEquipamentoDTO.Id), nameof(TipoEquipamentoDTO.Descricao), equipEdit.TipoEquipamentoDto.Id);

            var vSituation = await _handlerSituation.GetAllSituation();
            ViewBag.ValuesSituation = new SelectList(vSituation, nameof(SituacaoDTO.Id), nameof(SituacaoDTO.Descricao), equipEdit.SituacaoDto.Id);

            return View(equipEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EditEquipamentoDTO editEquipmentDTO)
        {
            _handlerEquipment.UpdateEquipment(editEquipmentDTO);
            return RedirectToAction(nameof(Index));
        }
    }
}

TMAN.LABOPS.FRONT.WEBUI/Tman.LabOps.WebUI.MVC/Controllers/ManufacturerController.cs
using Microsoft.AspNetCore.Mvc;
using Tman.LabOps.Infrastructure.CrossCutting.DTOs.Fabricante;
using Tman.LabOps.WebUI.Application.Interfaces;
using Tman.LabOps.WebUI.MVC.Controllers;

#pragma warning disable IDE0290

namespace LabOps.WebUI.Controllers
{
    [Route("Fabricante")]
    public class ManufacturerController : Controller
    {
        private readonly IHandlerManufacturer _handler;

        public ManufacturerController(IHandlerManufacturer handler)
        {
            _handler = handler;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("Cadastro")]
        public IActionResult RegisterManufacturer()
        {
            return View();
        }

        [HttpPost("Cadastro")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterManufacturer(NewFabricanteDTO newManufacturer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _handler.RegisterManufacturer(newManufacturer);
                    return RedirectToAction(nameof(HomeController.Index));
                }
                catch (Exception ex)
                {
                    TempData["MsgError"] = $"Ops, houve um erro. Detalhe do erro: {ex.Message}";
                    return RedirectToAction(nameof(Index));
                }
            }
            TempData["MsgError"] = $"Verifique se os dados estão corretos";
            return RedirectToAction(nameof(RegisterManufacturer));
        }

        [HttpGet("Atualizar")]
        public IActionResult UpdateManufacturer()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateManufacturer(EditFabricanteDTO editManufacturer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _handler.UpdateManufacturer(editManufacturer);
                    return RedirectToAction(nameof(HomeController.Index));
                }
                catch (Exception ex)
                {
                    TempData["MsgError"] = $"Ops, houve um erro. Detalhe do erro: {ex.Message}";
                    return RedirectToAction(nameof(Index));
                }
            }
            TempData["MsgError"] = $"Verifique se os dados estão corretos";
            return RedirectToAction(nameof(RegisterManufacturer));
        }
    }
}

TMAN.LABOPS.FRONT.WEBUI/Tman.LabOps.WebUI.MVC/Views/Shared/Components/NavMenu/Default.cshtml
<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: black; font-weight: bold;">LabOps</a>

<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>

        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Equipment" asp-action="Index">Equipamentos</a>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: black">Cadastros</a>
            <ul class="dropdown-menu">
                <li>
                    <a class="dropdown-item" asp-area="" asp-controller="Manufacturer" asp-action="RegisterManufacturer">Fabricante</a>
                </li>
                <li>
                    <a class="dropdown-item" asp-area="" asp-controller="TipoEquipamento" asp-action="Index">Tipo de Equipamento</a>
                </li>
                <li>
                    <a class="dropdown-item" asp-area="" asp-controller="Situacao" asp-action="Index">Situações</a>
                </li>
            </ul>
        </li>

        <li class="nav-item dropdown" aria-disabled="true">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" disabled style="color: darkgray">Administração</a>
            <ul class="dropdown-menu">
                <li>
                    <a class="dropdown-item" asp-area="" asp-controller="" asp-action="Cadastro">Usuarios</a>
                </li>
            </ul>
        </li>

    </ul>
</div>